---
title: "Prediksi Buku"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    social: menu
    vertical_layout: fill
    orientation: columns
runtime: shiny

---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(DT)
library(dplyr)
library(plotly)
library(readxl)
```
CV. Pratama Mitra Asara
===================================================================

### Prediksi Buku
```{r data}
bisa <- read_excel("E:/Skripsi/R Shiny/oke2.xlsx")

variabel <- c("Stok_Awal2018","Stok_Awal2019")

```

```{r inputs}

selectInput("pilih_variabel", label = h5("Pilih satu atau lebih variabel"),
            choices = variabel, variabel[1], multiple = TRUE)
```

```{r reactive expression}

model1 <- reactive({
  vars <- as.matrix(bisa[, input$pilih_variabel])
  lm(Stok_Awal2020 ~ vars, data = bisa)
})
```
Column {data-width=400}
-----------------------------------------------------------------------

###
```{r model output}
renderPrint({
  summary(model1())
})
```

###

```{r table}
DT::renderDataTable({
  
  DT::datatable(bisa%>% 
                  mutate(predicted = predict(model1()),residuals = residuals(model1())) %>% 
                  select(Nama_Buku, Stok_Awal2020, predicted, residuals), rownames = FALSE, colnames = c('Nama_Buku','Stok_Awal2020', 'Stok Prediksi', 'Residuals'), extensions = c('Buttons', 'Responsive'),options = list(columnDefs = list(list(className = 'dt-center', targets = "_all")), dom = 'Blfrt',buttons = c('copy', 'csv', 'excel', 'print'), searching = FALSE, lengthMenu = c(10, 20, 30, nrow(bisa)), scrollY = 300, scrollCollapse = TRUE))
})
```

Column {data-width=400}
-----------------------------------------------------------------------

###

```{r scatter, message=TRUE, warning=TRUE, paged.print=FALSE}
renderPlotly({
  plot_ly(data = bisa, y = ~predict(model1()), x = ~Stok_Awal2020,
          type = "scatter", mode = "markers",
          marker = list(size = 5,
                        color = '#FFFFFF',
                        line = list(color = '#EA6345',
                                    width =2))) %>%
    layout(title = '',
           yaxis = list(zeroline = FALSE, title = "Bismillah Prediksi", titlefont = list(
             family = "Lucida Console, Courier New, monoscape", size = 12, color = "#FFFFFF"), tickfont = list(family = "Lucida Console, Courier New, monoscape", size = 10, color = "#FFFFFF"), color = "white", size = 2),
           xaxis = list(zeroline = FALSE, title = "Stok", titlefont = list(family = "Lucida Console, Courier New, monoscape", size = 12, color = "#FFFFFF"), tickfont = list(family = "Lucida Console, Courier New, monoscape", size = 10, color = "#FFFFFF"), color = "white", size = 7)) %>%
    layout(plot_bgcolor='#678EB9', paper_bgcolor='#678EB9')
})
```

###

```{r histogram}
renderPlotly({
  plot_ly(bisa, x = ~round(residuals(model1()),2),type = "histogram", marker = list(color = "#EA6345",
                                                                                    line = list(color = "#FFFFFF", width = 1))) %>% layout(title='',
                                                                                                                                           yaxis = list(zeroline = FALSE, title = "frequency", titlefont = list(family = "Lucida Console, Courier New, monoscape", size = 12, color = "#FFFFFF"),
                                                                                                                                                                                                                          tickfont = list(family = "Lucida Console, Courier New, monoscape", size = 10, color = "#FFFFFF"), color = "white"),
                                                                                                                                                                 xaxis = list(zeroline = FALSE, title = "residual", titlefont = list(family = "Lucida Console, Courier New, monoscape", size = 12, color = "#FFFFFF" ),
                                                                                                                                                                             tickfont = list(family = "Lucida Console, Courier New, monoscape", size = 10, color = "#FFFFFF"), color = "white")) %>%
                                                                                                                                             layout(plot_bgcolor='#678EB9', paper_bgcolor='#678EB9')
})
```
